<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.evolutionnext</groupId>
        <artifactId>event-driven-architecture</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>customer-order-consumer</artifactId>
    <packaging>jar</packaging>

    <name>customer-order-consumer</name>
    <url>https://github.com/dhinojosa/event-driven-architecture</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.confluent</groupId>
                <artifactId>kafka-schema-registry-maven-plugin</artifactId>
                <version>8.1.0</version>
                <executions>
                    <execution>
                        <id>download-schemas</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>download</goal>
                        </goals>
                        <configuration>
                            <schemaRegistryUrls>
                                <param>http://127.0.0.1:8081</param>
                            </schemaRegistryUrls>
                            <subjectPatterns>
                                <param>^orders-(key|value)$</param>
                                <param>order</param>
                                <param>orderCancelled</param>
                                <param>orderItem</param>
                                <param>orderPlaced</param>
                            </subjectPatterns>
                            <versions>
                                <param>latest</param>
                                <param>latest</param>
                                <param>latest</param>
                                <param>latest</param>
                                <param>latest</param>
                            </versions>
                            <outputDirectory>${project.basedir}/src/main/avro</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>schema</goal>
                        </goals>
                        <configuration>
                            <sourceDirectory>${project.basedir}/src/main/avro</sourceDirectory>
                            <outputDirectory>${project.build.directory}/generated-sources/avro</outputDirectory>
                            <imports>
                                <import>${project.basedir}/src/main/avro/orderItem.avsc</import>
                                <import>${project.basedir}/src/main/avro/order.avsc</import>
                                <import>${project.basedir}/src/main/avro/orderCancelled.avsc</import>
                                <import>${project.basedir}/src/main/avro/orderPlaced.avsc</import>
                                <import>${project.basedir}/src/main/avro/orders-value.avsc</import>
                            </imports>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
