{
    "type": "record",
    "name": "StockChangedMessage",
    "namespace": "com.evolutionnext.inventory.events",
    "fields": [
        {
            "name": "productId",
            "type": {
                "type": "string",
                "logicalType": "uuid"
            }
        },
        {
            "name": "stock",
            "type": "int"
        },
        {
            "name": "timestamp",
            "type": {
                "type": "long",
                "logicalType": "timestamp-millis"
            }
        }
    ]
}
