<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.evolutionnext</groupId>
        <artifactId>event-driven-architecture</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>order</artifactId>
    <packaging>jar</packaging>

    <name>orders</name>
    <url>https://github.com/dhinojosa/event-driven-architecture</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.15.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.15.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.15.0</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.evolutionnext</groupId>
            <artifactId>web-util</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro-maven-plugin</artifactId>
                <configuration>
                    <sourceDirectory>${project.basedir}/src/main/avro</sourceDirectory>
                    <imports>
                        <import>${project.basedir}/src/main/avro/OrderItem.avsc</import>
                        <import>${project.basedir}/src/main/avro/Order.avsc</import>
                        <import>${project.basedir}/src/main/avro/OrderCancelled.avsc</import>
                        <import>${project.basedir}/src/main/avro/OrderPlaced.avsc</import>
                        <import>${project.basedir}/src/main/avro/OrderEvent.avsc</import>
                    </imports>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>io.confluent</groupId>
                <artifactId>kafka-schema-registry-maven-plugin</artifactId>
                <version>8.1.0</version>
                <configuration>
                    <schemaRegistryUrls>
                        <param>http://127.0.0.1:8081</param>
                    </schemaRegistryUrls>
                    <subjects>
                        <orders-value>src/main/avro/OrderEvent.avsc</orders-value>
                        <order>src/main/avro/Order.avsc</order>
                        <orderItem>src/main/avro/OrderItem.avsc</orderItem>
                        <orderCancelled>src/main/avro/OrderCancelled.avsc</orderCancelled>
                        <orderPlaced>src/main/avro/OrderPlaced.avsc</orderPlaced>
                    </subjects>
                    <schemaTypes>
                        <orders-value>AVRO</orders-value>
                        <order>AVRO</order>
                        <orderItem>AVRO</orderItem>
                        <orderCancelled>AVRO</orderCancelled>
                        <orderPlaced>AVRO</orderPlaced>
                    </schemaTypes>
                    <references>
                        <orders-value>
                            <reference>
                                <name>com.evolutionnext.order.events.OrderPlacedMessage</name>
                                <subject>orderPlaced</subject>
                            </reference>
                            <reference>
                                <name>com.evolutionnext.order.events.OrderCancelledMessage</name>
                                <subject>orderCancelled</subject>
                            </reference>
                        </orders-value>
                        <orderPlaced>
                            <reference>
                                <name>com.evolutionnext.order.events.OrderMessage</name>
                                <subject>order</subject>
                            </reference>
                        </orderPlaced>
                        <order>
                            <reference>
                                <name>com.evolutionnext.order.events.OrderItemMessage</name>
                                <subject>orderItem</subject>
                            </reference>
                        </order>
                    </references>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
