<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.evolutionnext</groupId>
        <artifactId>event-driven-architecture</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>inventory</artifactId>
    <packaging>jar</packaging>

    <name>inventory</name>
    <url>https://github.com/dhinojosa/event-driven-architecture</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <repositories>
        <repository>
            <id>confluent</id>
            <url>https://packages.confluent.io/maven/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>confluent</id>
            <url>https://packages.confluent.io/maven/</url>
        </pluginRepository>
    </pluginRepositories>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro-maven-plugin</artifactId>
                <configuration>
                    <sourceDirectory>${project.basedir}/src/main/avro</sourceDirectory>
                    <imports>
                        <import>${project.basedir}/src/main/avro/ProductCreated.avsc</import>
                        <import>${project.basedir}/src/main/avro/PriceChanged.avsc</import>
                        <import>${project.basedir}/src/main/avro/StockChanged.avsc</import>
                        <import>${project.basedir}/src/main/avro/InventoryEvent.avsc</import>
                    </imports>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>io.confluent</groupId>
                <artifactId>kafka-schema-registry-maven-plugin</artifactId>
                <version>8.1.0</version>
                <configuration>
                    <schemaRegistryUrls>
                        <param>http://127.0.0.1:8081</param>
                    </schemaRegistryUrls>
                    <subjects>
                        <inventory-value>src/main/avro/InventoryEvent.avsc</inventory-value>
                        <priceChanged>src/main/avro/PriceChanged.avsc</priceChanged>
                        <productCreated>src/main/avro/ProductCreated.avsc</productCreated>
                        <stockChanged>src/main/avro/StockChanged.avsc</stockChanged>
                    </subjects>
                    <schemaTypes>
                        <inventory-value>AVRO</inventory-value>
                        <priceChanged>AVRO</priceChanged>
                        <productCreated>AVRO</productCreated>
                        <stockChanged>AVRO</stockChanged>
                    </schemaTypes>
                    <references>
                        <inventory-value>
                            <reference>
                                <name>com.evolutionnext.inventory.events.ProductCreatedMessage</name>
                                <subject>productCreated</subject>
                            </reference>
                            <reference>
                                <name>com.evolutionnext.inventory.events.PriceChangedMessage</name>
                                <subject>priceChanged</subject>
                            </reference>
                            <reference>
                                <name>com.evolutionnext.inventory.events.StockChangedMessage</name>
                                <subject>stockChanged</subject>
                            </reference>
                        </inventory-value>
                    </references>
                </configuration>
                <goals>
                    <goal>register</goal>
                </goals>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.evolutionnext</groupId>
            <artifactId>web-util</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
